---
title: "Everyday in my life"
author: "yudalang"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
    number_sections: yes
    toc: yes
---

# 2017上半年

## 6月13日：支部大会

`给学弟学妹的讲话：` 

很高兴能够站在这里发言。
这次我主要是想谈谈三方面的事，我得承认每个人讲的往往会带有一定自己的感情色彩

### 关于本科的生活

教育部在2012年将我们的专业划为大致十二个学科门类。在大家熟知的理工农医就是四个自然科学门类。其中大家最熟知的理学便是我们通常所说的理科，工农医则是更多地按生产实践划分出来的学科。

对于现在一年快过去的大一的同学，大家有些同学可能非常地不情愿去学那些学科基础课，比如线性代数。可能大家想着专业嘛，就想着一些专业知识。其实不然作为一个大学的学生，我们当然不能只学一点技术。而且我可以告诉你们，那些重要的基础课正是以后你们理解更深的理论，提出新的理论所需要的很好的工具。对这些基础学科感到很枯燥的同学，我可以建议你们多去了解一些有趣的历史，借助于互联网去看看一门学科很有名的历史事件。

对于大二的同学你们这个时期正激励的是大学最迷茫的时期，同时也是很多地方会产生分化的时候。大学的学习也彻彻底底地成为了考前死记硬背的节奏。我希望你们这个时候，最好有自己的一些规划，比如争取出国也是个很好的选择。同时这里我也告诉你们，农学现在有机会转理学或工学，与信息农业注重收集数据有些不同的是，现代生物学有一门数学计算机与生物学的交叉学科兴起。如果你有那样的想法：“我不是数学物理不好来学生物的”，觉得可以往哪个方向发展。

对于大三的同学，我知道你们这个时候可能开始去思考那个本科生培养方案了。对那个农学的本科生培养方案都有自己的充分的建议。以前我也很有这种想法，但是每当我说出自己的想法的时候，总能得到一片反对的声音，理由各种各样。确实像农学这种注重生产实际的学科，你既要平衡基础生物和农学生产实践，同时你也要面对很多因为错选专业一直陷在农学专业的人。所以我觉得最好还是自己拥有一定的认知：而突破你认知局限的方法就是依靠语言。所以要多看书，多多利用互联网了解这个世界，多多交流，论坛贴吧可以好好利用。但是不可看太多贴吧成为五毛和愤青，最重要的还是脚踏实地。


### 关于保内与保外的对比

在中科院不用啃老；见识会广很多；身边985高校的人多；

南农就省一年，和联合培养比较吸引人


### 关于情感：

对于每个人最终所追求的东西：有思想的、有抱负的、能引起人情感共鸣的。我想最终达到的结果应该是一种能够让所有人都能够得到审美上的享受，然后是情感上的共鸣，这种享受我自己总结了一下概括为:简洁、高效和艺术感。

在情感上我还想告诫大家不要在认真执着地追求一样东西的时候，忘记了和你在乎的人培养培养感情。


有一句英语格言可以来说明这个原因：No matter how much money you make or how great your accomplishment are , you will not be able to enjoy your success if you don’t have loved ones to share it with.

虽然作为你们的学长学姐，这一届人走了。但是我们还会是你们亲爱的学长学姐。以后有什么问题都可以和我们交流，同时我再声明一下不用在乎我严肃的表情。

最后，在这大学里我总结了一段话送给大家：美好的东西最后往往能给人审美上的享受：简洁,高效,艺术感!
下列事物可供你们永恒地去追求：真理,真情,真知!乐观,开朗,正能量！自省,自律,自信！团结,友爱,坚持!
希望你们仰望星空，但亦脚踏实地。







